name: configs
on:
  push:
  schedule:
    - cron:  '0 12 * * *'
jobs:
  system:
    strategy:
      fail-fast: false
      matrix:
        machine: [xps, vultr]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0
    - name: Install nix
      uses: cachix/install-nix-action@v11
      with:
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20201221_9fab14a/install
        extra_nix_config: |
          experimental-features = nix-command flakes
    - name: Build system config
      run: nix build .#nixosConfigurations.${{ matrix.machine }}.config.system.build.toplevel
